name: movie_tournament_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  dio: ^5.8.0+1
  fpdart: ^1.1.1
  equatable: ^2.0.7
  get_it: ^8.0.3
  go_router: ^14.8.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
